#默认使用配置
spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL

server:
  port: 8090

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.aim.questionnaire.dao.entity
  mapperLocations: classpath:mapper/*.xml
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: true

# 分页配置
pagehelper:
  helperDalect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: conut=countSql

commonDS:
  # 配置初始化大小、最小、最大
  initialSize: 2
  minIdle: 2
  maxActive: 5
  #配置获取连接等待超时的时间
  maxWait: 60000
  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  #配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 60000

  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  #打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 5
  #配置监控统计拦截的filters，去掉后监控界面sql无法统计
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  useGlobalDataSourceStat: true
  #durid监控配置
  loginUsername: star
  loginPassword: Star1234
  resetEnable: false
  rootPath: /druid/*

---

#开发配置
spring:
  profiles: dev
  datasource:
    #    连接mysql5数据库
    #     url: jdbc:mysql://39.99.231.41:3306/questionnaire?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #     username: lying
    #     password: lying
    #     driver-class-name: com.mysql.cj.jdbc.Driver
    #连接mysql8数据库
#    url: jdbc:mysql://127.0.0.1:3306/questionnaire?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zejaw342xqoq8p8l6o.mysql.rds.aliyuncs.com/questionnaire?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: ljhlbx001
    driver-class-name: com.mysql.cj.jdbc.Driver


  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr:  localhost:8848
  application:
    name: project
  main:
    allow-bean-definition-overriding: true # Spring Boot 2.1 需要设定
  cloud:
    nacos:
      discovery:
        server-addr: 118.123.3.141:8848
        namespace: c67e4a97-a698-4d6d-9bb1-cfac5f5b51c4
        cluster-name: DEFAULT
      config:
        server-addr: 118.123.3.141:8848 # 配置中心地址
        file-extension: yaml
        namespace: c67e4a97-a698-4d6d-9bb1-cfac5f5b51c4 # 开发环境
        group: DEFAULT # xx业务组

